# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: "{{ .ProjectName }}"
    main: ./cmd/chatroom
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

archives:
  - name_template: >
      {{- .ProjectName }}_{{- .Version }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md

dockers:
  - image_templates:
      - "ghcr.io/cole-maxwell1/{{ .ProjectName }}:{{ .Tag }}-amd64"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.platform=linux/arm64"
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
      - "ghcr.io/cole-maxwell1/chatroom:{{ .Tag }}-arm64v8"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
  - name_template: ghcr.io/cole-maxwell1/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/cole-maxwell1/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/cole-maxwell1/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/cole-maxwell1/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/cole-maxwell1/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/cole-maxwell1/{{ .ProjectName }}:{{ .Version }}-arm64v8

checksum:
  name_template: "checksums.txt"

# create a source tarball
# https://goreleaser.com/customization/source/
source:
  enabled: true
